.class public Lcom/gentle/ppcat/AdNoOpPlugin;
.super Ljava/lang/Object;
.source "AdNoOpPlugin.java"

# FlutterPlugin (Lสۦۣ۟ۡ/สۥ۟۟ۡ;) + MethodChannel.MethodCallHandler (Lสۥ۠ۦۡ/สۥ۟۟۠$สۥ۟۟ۢ;)
# Generated by analysis_workdir/gen_stub.py from byte-exact obfuscated tokens.
.implements Lสۦۣ۟ۡ/สۥ۟۟ۡ;
.implements Lสۥ۠ۦۡ/สۥ۟۟۠$สۥ۟۟ۢ;


.method public constructor <init>()V
    .locals 0
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V
    return-void
.end method

# public void onAttachedToEngine(FlutterPluginBinding binding)
.method public ۥ้้้้้้้้้้้้้้้้้้้้้้۟۟ۡ(Lสۦۣ۟ۡ/สۥ۟۟ۡ$สۥ۟۠ۢ;)V
    .locals 3
    invoke-virtual {p1}, Lสۦۣ۟ۡ/สۥ۟۟ۡ$สۥ۟۠ۢ;->ۥ้้้้۟۟ۡ()Lสۥ۠ۦۡ/สۥ۟۠ۢ;
    move-result-object v0
    new-instance v1, Lสۥ۠ۦۡ/สۥ۟۟۠;
    const-string v2, "flutter_pangle_ads"
    invoke-direct {v1, v0, v2}, Lสۥ۠ۦۡ/สۥ۟۟۠;-><init>(Lสۥ۠ۦۡ/สۥ۟۠ۢ;Ljava/lang/String;)V
    invoke-virtual {v1, p0}, Lสۥ۠ۦۡ/สۥ۟۟۠;->ۥ้้้้้้้้้้۟۟ۡ(Lสۥ۠ۦۡ/สۥ۟۟۠$สۥ۟۟ۢ;)V
    new-instance v1, Lสۥ۠ۦۡ/สۥ۟۟۠;
    const-string v2, "ksad"
    invoke-direct {v1, v0, v2}, Lสۥ۠ۦۡ/สۥ۟۟۠;-><init>(Lสۥ۠ۦۡ/สۥ۟۠ۢ;Ljava/lang/String;)V
    invoke-virtual {v1, p0}, Lสۥ۠ۦۡ/สۥ۟۟۠;->ۥ้้้้้้้้้้۟۟ۡ(Lสۥ۠ۦۡ/สۥ۟۟۠$สۥ۟۟ۢ;)V
    new-instance v1, Lสۥ۠ۦۡ/สۥ۟۟۠;
    const-string v2, "plugins.flutter.io/google_mobile_ads"
    invoke-direct {v1, v0, v2}, Lสۥ۠ۦۡ/สۥ۟۟۠;-><init>(Lสۥ۠ۦۡ/สۥ۟۠ۢ;Ljava/lang/String;)V
    invoke-virtual {v1, p0}, Lสۥ۠ۦۡ/สۥ۟۟۠;->ۥ้้้้้้้้้้۟۟ۡ(Lสۥ۠ۦۡ/สۥ۟۟۠$สۥ۟۟ۢ;)V
    new-instance v1, Lสۥ۠ۦۡ/สۥ۟۟۠;
    const-string v2, "plugins.hetian.me/gdt_plugins"
    invoke-direct {v1, v0, v2}, Lสۥ۠ۦۡ/สۥ۟۟۠;-><init>(Lสۥ۠ۦۡ/สۥ۟۠ۢ;Ljava/lang/String;)V
    invoke-virtual {v1, p0}, Lสۥ۠ۦۡ/สۥ۟۟۠;->ۥ้้้้้้้้้้۟۟ۡ(Lสۥ۠ۦۡ/สۥ۟۟۠$สۥ۟۟ۢ;)V
    return-void
.end method

# public void onDetachedFromEngine(FlutterPluginBinding binding)
.method public ۥ้้้้้้้้้้้้้้้้۟۟ۡ(Lสۦۣ۟ۡ/สۥ۟۟ۡ$สۥ۟۠ۢ;)V
    .locals 0
    return-void
.end method

# public void onMethodCall(MethodCall call, Result result) -> result.success(null)
.method public ۥ้้้้้้้้้้้้้้้้้้۟۟ۡ(Lสۥ۠ۦۡ/สۥ۟۠۠;Lสۥ۠ۦۡ/สۥ۟۟۠$สۥۣ۟۟;)V
    .locals 1
    const/4 v0, 0x0
    invoke-interface {p2, v0}, Lสۥ۠ۦۡ/สۥ۟۟۠$สۥۣ۟۟;->ۥ้้้้۟۟ۡ(Ljava/lang/Object;)V
    return-void
.end method
