#!/usr/bin/env python3
"""Generate AdNoOpPlugin.smali by reading EXACT obfuscated method-name tokens
from the existing (working) smali, guaranteeing byte-exact interface compliance.

Strategy: a FlutterPlugin(MethodCallHandler) that, on attach, creates a MethodChannel
for each ad channel name with PLAIN const-strings and sets itself as handler.
onMethodCall replies result.success(null) to everything -> no MissingPluginException.
If the class fails to verify/load, the registrant's try/catch swallows it (no crash)."""
import re, os

APK = '/root/tools/ppcat_apktool'
def rd(p): return open(os.path.join(APK,p), encoding='utf-8').read()

# ---- Extract exact tokens from interface / working-plugin smali ----
flutter_plugin_iface = 'Lสۦۣ۟ۡ/สۥ۟۟ۡ;'
mch_iface           = 'Lสۥ۠ۦۡ/สۥ۟۟۠$สۥ۟۟ۢ;'
binding_cls         = 'Lสۦۣ۟ۡ/สۥ۟۟ۡ$สۥ۟۠ۢ;'
mchannel_cls        = 'Lสۥ۠ۦۡ/สۥ۟۟۠;'
bmessenger_cls      = 'Lสۥ۠ۦۡ/สۥ۟۠ۢ;'
mcall_cls           = 'Lสۥ۠ۦۡ/สۥ۟۠۠;'
result_iface        = 'Lสۥ۠ۦۡ/สۥ۟۟۠$สۥۣ۟۟;'

# FlutterPlugin's two abstract methods (attach/detach). The longer-name one = onAttachedToEngine
fp_src = rd('smali_classes2/สۦۣ۟ۡ/สۥ۟۟ۡ.smali')
fp_methods = re.findall(r'\.method public abstract (\S+)\(Lสۦۣ۟ۡ/สۥ۟۟ۡ\$สۥ۟۠ۢ;\)V', fp_src)
assert len(fp_methods)==2, fp_methods
attach_name = max(fp_methods, key=len)   # more ้'s = onAttachedToEngine (verified: sqflite 3256)
detach_name = min(fp_methods, key=len)   # onDetachedFromEngine (sqflite 2893)

# MethodCallHandler.onMethodCall name
mch_src = rd('smali_classes2/สۥ۠ۦۡ/สۥ۟۟ۡ$สۥ۟۟ۢ.smali')  # wait, file is สۥ۟۟۠$...
mch_src = rd('smali_classes2/สۥ۠ۦۡ/สۥ۟۟۠$สۥ۟۟ۢ.smali')
onmethod_name = re.search(r'\.method public abstract (\S+)\(Lสۥ۠ۦۡ/สۥ۟۠۠;Lสۥ۠ۦۡ/สۥ۟۟۠\$สۥۣ۟۟;\)V', mch_src).group(1)

# getBinaryMessenger on binding: binding->X()LBinaryMessenger;
sq = rd('smali_classes2/สۥ۟ۥۥ/สۥ۟۟ۢ.smali')
getbm = re.search(r'invoke-virtual \{p1\}, Lสۦۣ۟ۡ/สۥ۟۟ۡ\$สۥ۟۠ۢ;->(\S+)\(\)Lสۥ۠ۦۡ/สۥ۟۠ۢ;', sq).group(1)
# setMethodCallHandler on MethodChannel: channel->X(MethodCallHandler)V
setmch = re.search(r'Lสۥ۠ۦۡ/สۥ۟۟۠;->(\S+)\(Lสۥ۠ۦۡ/สۥ۟۟۠\$สۥ۟۟ۢ;\)V', sq).group(1)

# Result.success(Object)V
res_src = rd('smali_classes2/สۥ۠ۦۡ/สۥ۟۟۠$สۥۣ۟۟.smali')
success_name = re.search(r'\.method public abstract (\S+)\(Ljava/lang/Object;\)V', res_src).group(1)

print('attach  =', repr(attach_name), 'len', len(attach_name))
print('detach  =', repr(detach_name), 'len', len(detach_name))
print('onMethod=', repr(onmethod_name))
print('getBM   =', repr(getbm))
print('setMCH  =', repr(setmch))
print('success =', repr(success_name))

# channels to no-op (MethodChannels only)
CHANNELS = [
    'flutter_pangle_ads',
    'ksad',
    'plugins.flutter.io/google_mobile_ads',
    'plugins.hetian.me/gdt_plugins',
]

# build the onAttachedToEngine body: for each channel, new MethodChannel(bm,name).setHandler(this)
attach_body = []
attach_body.append(f'    .locals 3')
attach_body.append(f'    invoke-virtual {{p1}}, {binding_cls}->{getbm}(){bmessenger_cls}')
attach_body.append(f'    move-result-object v0')
for ch in CHANNELS:
    attach_body.append(f'    new-instance v1, {mchannel_cls}')
    attach_body.append(f'    const-string v2, "{ch}"')
    attach_body.append(f'    invoke-direct {{v1, v0, v2}}, {mchannel_cls}-><init>({bmessenger_cls}Ljava/lang/String;)V')
    attach_body.append(f'    invoke-virtual {{v1, p0}}, {mchannel_cls}->{setmch}({mch_iface})V')
attach_body.append(f'    return-void')

smali = f'''.class public Lcom/gentle/ppcat/AdNoOpPlugin;
.super Ljava/lang/Object;
.source "AdNoOpPlugin.java"

# FlutterPlugin ({flutter_plugin_iface}) + MethodChannel.MethodCallHandler ({mch_iface})
# Generated by analysis_workdir/gen_stub.py from byte-exact obfuscated tokens.
.implements {flutter_plugin_iface}
.implements {mch_iface}


.method public constructor <init>()V
    .locals 0
    invoke-direct {{p0}}, Ljava/lang/Object;-><init>()V
    return-void
.end method

# public void onAttachedToEngine(FlutterPluginBinding binding)
.method public {attach_name}({binding_cls})V
{chr(10).join(attach_body)}
.end method

# public void onDetachedFromEngine(FlutterPluginBinding binding)
.method public {detach_name}({binding_cls})V
    .locals 0
    return-void
.end method

# public void onMethodCall(MethodCall call, Result result) -> result.success(null)
.method public {onmethod_name}({mcall_cls}{result_iface})V
    .locals 1
    const/4 v0, 0x0
    invoke-interface {{p2, v0}}, {result_iface}->{success_name}(Ljava/lang/Object;)V
    return-void
.end method
'''

out = '/root/tools/ppcat_apktool/smali/com/gentle/ppcat/AdNoOpPlugin.smali'
open(out,'w',encoding='utf-8').write(smali)
print('\nwrote', out)
print('--- preview ---')
print(smali)
